name: 'Setup Node and npm'
description: 'Checkout code, setup Node.js, install dependencies'
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies in root
      run: npm install
      shell: bash

    - name: Set working directory to functions
      run: cd functions
      shell: bash

    - name: Install Dependencies in functions
      run: npm install
      shell: bash
