name: Checks
on: pull_request

jobs:
  format:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Run Prettier Check
        run: npm run format
        working-directory: functions

  lint:
    name: Check Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Run ESLint Check
        run: npm run lint
        working-directory: functions

  build:
    name: Check Project Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Run Build
        run: npm run build
        working-directory: functions

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Run Tests
        run: npm test
        working-directory: functions

  test-emulators:
    name: Run Tests:Emulators
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Run test:emulators
        run: npm run test:emulators
        working-directory: functions

  validate-pr:
    name: Check PR Source for 'main' originates from 'stage'
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    steps:
      - run: |
          if [ "${{ github.head_ref }}" != "stage" ]; then
            echo "Error: PR to main must originate from the 'stage' branch."
            exit 1
          fi
