name: Deploy to Firebase Functions on push
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Create local .env file from secrets
        run: |
          echo "SEARCH_ALGOLIA_APP_ID=${{ secrets.SEARCH_ALGOLIA_APP_ID }}" > .env.firetest-44
          echo "APPLICATION_SERVICE_USER_ID=${{ secrets.APPLICATION_SERVICE_USER_ID }}" >> .env.firetest-44
        working-directory: functions

      - name: Deploy to Firebase Functions
        run: npx firebase deploy --only functions
