name: Deploy to Firebase Functions on push
on:
  push:
    branches: [stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Write Service Account Key file
        run: |
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $GITHUB_WORKSPACE/firebase-service-account.json

      - name: Deploy to Firebase Functions
        run: npx firebase deploy --only functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/service-account.json
