name: Deploy to Firebase Functions on push
on:
  push:
    branches: [main, stage]

jobs:
  build_and_deploy:
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Create credentials.json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "credentials.json"
          json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set environment variable with path to credentials.json
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(readlink -f credentials.json)" >> $GITHUB_ENV

      - name: Deploy to Firebase
        run: npx firebase deploy --only functions
