name: Deploy to Firebase Functions on push
on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Deploy Functions
        run: npx firebase-tools deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
