name: Deploy to Firebase Functions on push
on:
  push:
    branches: [stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Write Service Account Key file
        run: |
          echo "$SERVICE_ACCOUNT" > "${GITHUB_WORKSPACE}/service-account.json"
          export GOOGLE_APPLICATION_CREDENTIALS="${GITHUB_WORKSPACE}/service-account.json"
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Deploy to Firebase Functions
        run: |
          echo "-- debug credentials path"
          cat $GOOGLE_APPLICATION_CREDENTIAL
          echo "-- debug credentials content"
          cat ${GITHUB_WORKSPACE}/service-account.json
          echo "-- start deploy"
          npx firebase deploy --only functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${GITHUB_WORKSPACE}/service-account.json
