name: Deploy to Firebase Functions on push
on:
  push:
    branches: [main]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Create local .env file from secrets
        run: |
          echo "APPLICATION_IDD=${{ secrets.APPLICATION_IDD }}" > ${{ env.ENV_FILE }}
          echo "SERVICE_ID=${{ secrets.SERVICE_ID }}" >> ${{ env.ENV_FILE }}
        working-directory: functions
        env:
          ENV_FILE: .env.firetest-44

      - name: Deploy to Firebase Functions
        run: npx firebase deploy --only functions
