name: Deploy to Firebase Functions on push
on:
  push:
    branches: [main, stage]

jobs:
  build_and_deploy:
    name: Deploy to Firebase Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Set up Service Account Credentials
        run: |
          echo "${GCP_SA_KEY}" > ${HOME}/gcp-key.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Functions
        run: npx firebase-tools deploy --only functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/gcp-key.json
