name: Deploy to Firebase Functions on push
on:
  push:
    branches: [stage]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-node-npm

      - name: Write Service Account Key file
        run: |
          echo "SERVICE_ACCOUNT" > "${HOME}/service-account.json"
          export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/service-account.json"
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Deploy to Firebase Functions
        run: |
          # debug credentials path
          echo $GOOGLE_APPLICATION_CREDENTIALS
          # debug credentials content
          cat ${HOME}/service-account.json
          npx firebase deploy --only functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${HOME}/service-account.json
